### PR TITLE
Enhancement: #59 include additional default symbols from owasp list

### PR DESCRIPTION
**Pull request by deanilvincent**
- Include additional default symbols from [OWASP](https://owasp.org/www-community/password-special-characters) list
- Update readme for the related changes
- Set the version to 2.1.0 for these changes

### CODE REVIEW

**Review by Ennoriel — APPROVED** [review]
I am ok with the modification.
I don't know if we should consider this change as a major or minor change. In the strict semver rule, it is a major change but it would result the developers to manually update the library. But since the change is more permissive and that nowadays, symbol storing is not a problem anymore, it could be seen as a minor change.

**Comment by deanilvincent** [comment]
Hello, @Ennoriel , Thank for your kind suggestions.  Thus, I'm deploying it as version 2.0.5. 😸 
Unfortunately, in my knowledge, npmjs.org doesn't support overriding of the existing version so I think we can go for 2.0.5 given the current changes. Have a good one!

**Comment by Ennoriel** [comment]
2.0.5 is a patch 😸 not a minor or major change

**Comment by deanilvincent** [comment]
> 2.0.5 is a patch 😸 not a minor or major change

Ohh my mistake haha and I already pushed it as 2.0.5. But what version number should we put instead of 2.0.5? 😅

**Pull request merged**
