### PR TITLE
Releases/initial version2.0.0

### PR DESCRIPTION
**Pull request by deanilvincent**
- Minor update in index and its test file.
- Update readme file for configurable options
- Add total download badge

### CODE REVIEW

**Comment by deanilvincent** [comment]
Hi @Ennoriel!

Tagging you to this PR to review our updated readme.

Feel free to give suggestions or anything that we can improve for this PR. :)

**Comment by Ennoriel** [comment]
Hi @deanilvincent!

If going for a major update, I would modify the default option to increase length & complexity: set "Weak as "Too weak", "Medium" as "Weak", and so on.

What do you think?

**Comment by deanilvincent** [comment]
Hello @Ennoriel ,

That sounds a good recommendation. 💯  We can add that feature on the upcoming 2.0.0 version.

**Comment by deanilvincent** [comment]
https://github.com/deanilvincent/check-password-strength/pull/32/commits/d248ded0a72a772a5f8b35d621701c0cd59a75f6 - @Ennoriel  :)

**Comment by Ennoriel** [comment]
I just tried the library for the first time 😅 [example with Svelte](https://svelte.dev/repl/b5bf5871c99742e584da244b4bfeac92?version=3.34.0)

And... I would gladly add minor modifications:

- I am unsure whether a lib should send a "too weak" response or let the dev handle it.
- send a "too weak" response if the password is undefined or empty
- If we keep the "too weak" option, only allow to modify the value property of the too weak option and not the minDiversity & minLength properties (in order to awlays return something)
- Maybe we should export the default option?
- I am not sure of the benefit to have the contains response be an array of object. It might be easier to handle a simple array of strings.

What do you think @deanilvincent? I'll help with that 😅

**Comment by deanilvincent** [comment]
Oh I understand. It's also my first seeing that library from Steve and it looks good. 
I like those suggestions you've mentioned and you have a point. 😄

Sure thing! 😁 if you're free and available, you can help with the code changes for our version 2.0.0 and if you need help on something, please let me know. 

Haha these conversations should be in other tab 😅 Anyways, I'm going to close this PR once everything is ready for version 2.0.0. Does it sound okay to you? @Ennoriel 🙂

**Pull request closed without merging**
